import { DEFAULT_DECISIONS_CONFIG } from '../config.js';

function bool(value: boolean): string {
  return value ? 'true' : 'false';
}

/** Complete installer-owned append fragment; every supported key is taught here. */
export function decisionsConfigTemplate(enabled = false): string {
  const defaults = DEFAULT_DECISIONS_CONFIG;
  return [
    '# Optional Jev decision routing. Default OFF: deterministic behavior, zero decision requests.',
    '# Credentials never belong in TOML. Store locally with:',
    '#   node dist/decisions/cli.js credentials set --stdin              # openrouter slot',
    '#   node dist/decisions/cli.js credentials set --slot typesafe --stdin',
    '[decisions.jev]',
    `enabled = ${bool(enabled)} # One reversible flag. false never resolves credentials or contacts the provider.`,
    `model = "${defaults.jev.model}" # OpenRouter Jev alias; feeds the openrouter-jev profile below.`,
    `endpoint = "${defaults.jev.endpoint}" # Credential-bearing traffic is restricted to this exact HTTPS endpoint.`,
    `timeout_ms = ${defaults.jev.timeoutMs} # Per-call hard limit; timeout falls back deterministically.`,
    '',
    '# Provider profiles (issue #222). Built-ins always exist: openrouter-jev',
    '# (default), typesafe-direct and local. Override one by re-declaring it;',
    '# define your own under a new name. Probe any of them with:',
    '#   node dist/decisions/cli.js check --profile <name>',
    '# [decisions.providers.typesafe-direct]',
    '# protocol = "systemone"',
    '# endpoint = "https://api.typesafe.ai/v1/systemone"',
    '# model = "jev-latest"',
    '# credential = "typesafe" # env TYPESAFE_API_KEY or credentials/typesafe.key; bound to api.typesafe.ai',
    '# timeout_ms = 2000',
    '# input_price_per_mtok = 0.042 # cost fallback when a response carries no usage.cost',
    '#',
    '# [decisions.providers.local]',
    '# protocol = "systemone"',
    '# endpoint = "http://127.0.0.1:8088/v1/systemone"',
    '# model = "laya-421m"',
    '# credential = "none" # keyless is allowed ONLY for loopback hosts',
    '# timeout_ms = 2000',
    '',
    '# Per-surface routing and mode (issues #222/#223). Unlisted surfaces ride',
    '# the openrouter-jev profile with the pre-#223 behavior (provider answer,',
    '# deterministic fallback, no enforce gate). Explicit modes: "off"',
    '# (deterministic only, no provider call), "shadow" (the provider is asked',
    '# and recorded to the ledger as decisions.shadow, but the deterministic',
    '# answer is served — behavior cannot change), and "enforce" (the provider',
    '# answer routes; REQUIRES a recorded backtest meeting its stated threshold',
    '# at <data_dir>/decisions/backtests/<surface>.json or every request fails',
    '# loud). Produce that evidence with:',
    '#   node dist/decisions/cli.js extract-cases --surface <s> --out <jsonl>',
    '#   node dist/decisions/cli.js backtest --surface <s> --profile <p> --cases <jsonl> --threshold <min> --save',
    '# [decisions.surfaces]',
    '# event_triage = "openrouter-jev"                    # shorthand: routing only',
    '# [decisions.surfaces.event_triage]',
    '# provider = "openrouter-jev"',
    '# mode = "shadow"',
    '',
    '# Read-only classification: mistakes are recoverable, so confidence bars are lower.',
    '[decisions.thresholds.read_only]',
    `act = ${defaults.thresholds.read_only.act} # metric >= act enters the high band.`,
    `confirm = ${defaults.thresholds.read_only.confirm} # confirm <= metric < act flags for confirmation.`,
    `require_confirm_on_act = ${bool(defaults.thresholds.read_only.requireConfirmOnAct)} # High read-only routes need no added confirmation.`,
    '',
    '# Operational routing can spend turns/quota or alter restart guidance.',
    '[decisions.thresholds.operational]',
    `act = ${defaults.thresholds.operational.act} # High-confidence operational guidance is eligible within existing authority.`,
    `confirm = ${defaults.thresholds.operational.confirm} # Medium confidence flags; below this uses deterministic fallback.`,
    `require_confirm_on_act = ${bool(defaults.thresholds.operational.requireConfirmOnAct)} # Existing operational guards still apply.`,
    '',
    '# Destructive routing never grants permission: every passable band still requires a human.',
    '[decisions.thresholds.destructive]',
    `act = ${defaults.thresholds.destructive.act} # High bar for destructive triage.`,
    `confirm = ${defaults.thresholds.destructive.confirm} # Medium band pauses/asks; below uses deterministic fallback.`,
    `require_confirm_on_act = ${bool(defaults.thresholds.destructive.requireConfirmOnAct)} # Must stay true; config validation rejects false.`,
    '',
  ].join('\n');
}
